### ISSUE TITLE
IP Address Report

### ISSUE THREAD

**Issue by lavermil** [AsBuiltReport/AsBuiltReport.Nutanix.PrismCentral#1]
**New Feature Request:**
**Is your feature request related to a problem? Please describe.**
It is always important to know the current usage of IP addressing in subnets. Collecting information can be difficult.

**Describe the solution you'd like**
It would be really useful to have an IP address Report as part of the export. This would allow for easy input into a IPAM, spread sheet, DB, etc. The idea would be to have this in a list of individual IPs. So each IP address would be on a line/row of its own.
Maybe the columns would be something like below.
IP(v4/v6),VMName,vNIC,VLAN#,SubnetName,IPAMMethod,vSwitch,Node/Host,Cluster,Location

**Describe alternatives you've considered**
Writing my own script to do the same thing but this is a nice solution and would benefit others so coding in a vacuum is not ideal.

**Additional context**
None

**Comment by tpcarman** [comment]
AsBuiltReport relies on [PScribo](https://github.com/iainbrighton/PScribo), to produce the document outputs. At present there is no ability, nor plans to support an export feature for Excel. While I have considered a feature like this, it simply would not work within the current framework, and therefore I do not plan to implement it.
